javac TTS.java
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
java TTS Input/input1.txt
